version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    volumes:
      - ./synapse-data:/data
    ports:
      - 8008:8008

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - 8448:8448
    volumes:
      - ./matrix.conf:/etc/nginx/conf.d/matrix.conf
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/keys/:/etc/nginx/ssl/

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding='UTF8' --lc-collate='C' --lc-ctype='C'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
