version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx-conf/certbot.conf:/etc/nginx/conf.d/certbot.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/keys:/etc/nginx/ssl/
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/keys:/etc/letsencrypt/
